server:
  port: 8093
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BootcampJreyes/repository.git
          username: jordyreyesju
          password: Jre181731994+
          default-label: main
  profiles:
    active: git